version: '3'
tasks:
    default:
        cmds:
        - task: test
        - task: build

    help:
        silent: true
        cmds:
            - task --list-all
    setup:
        ignore_error: true
        cmds:
            - pipenv install --dev
            - sudo apt-get install git-secret -y
            - pipenv run pre-commit install -t pre-commit
            - pipenv run pre-commit install -t pre-push
            - pip install pipenv
            - pipenv install --deploy --dev

    show_secrets:
        - git secret reveal -f
    save_secrets:
        - git secret hide -m -d

    test:
        env:
            PIPENV_VERBOSITY: -1
        cmds:
            - pipenv run isort --recursive --diff .
            - pipenv run black --check .
            - pipenv run flake8
            - pipenv run mypy
            - pipenv run pytest --cov --cov-fail-under=100
    build:
        cmds:
            - sudo docker build . -t porch_light:latest
            - sudo docker run --rm porch_light:latest
