version: '3'
includes:
    docker: ./TaskfileDocker.yaml
    deploy: ./TaskfileDeploy.yaml

tasks:
    default:
        cmds:
            -   task: test
            -   task: docker:build
    help:
        silent: true
        cmds:
            - task --list-all
    deploy:
        - task: deploy:deploy
    # Dev
    setup:
        env:
            PIPENV_IGNORE_VIRTUALENVS: 1
        ignore_error: true
        cmds:
            - pip install pipenv
            - sudo apt-get install git-secret -y
            - pipenv install --dev
            - pipenv run pre-commit uninstall
            - pipenv run pre-commit clean
            - pipenv run pre-commit install
    remove_hooks:
        ignore_error: true
        cmds:
            - pipenv run pre-commit uninstall
            - pipenv run pre-commit clean
            - rm .git/hooks -rf
    show_secrets:
        - git secret reveal -f
    save_secrets:
        - git secret hide -m -d
    update_pipfile:
        - rm Pipfile
        - rm Pipfile.lock
        - pip freeze > requirements.txt
        - pipenv install --dev -r requirements.txt
        - rm requirements.txt

    # Test
    test:
        cmds:
            -   task: show_secrets
            -   task: test-run
    test-run:
        # We get our secrets from env vars
        # These either get loaded by the python module itself, or via GH Actions
        silent: false
        interactive: true
        env:
            PIPENV_VERBOSITY: -1
        cmds:
            - pipenv run isort --recursive --diff .
            - pipenv run black .
            - pipenv run mypy --install-types --non-interactive
            - pipenv run pytest --cov --cov-fail-under=75
    # CICD Stuff
    github:
        ignore_error: true
        cmds:
            - task: test-run
    commit:
        -   task: save_secrets
        -   task: show_secrets
    push:
        -   task: show_secrets
#        -   task: test
#        -   task: save_secrets
#        - pipenv run flake8 # Only be picky during push
