version: '3'
tasks:
#    default:
    #      cmds:
    #      - task: test

    help:
        silent: true
        cmds:
            - task --list-all
            - echo "For import and destroy, you need to put -- between the task and the arg, ex (task import -- blah)"
    setup:
        ignore_error: true
        cmds:
            - pipenv install --dev
            - sudo apt-get install git-secret -y
            - pipenv run pre-commit install -t pre-commit
            - pipenv run pre-commit install -t pre-push

    show_secrets:
        - git secret reveal -f
    save_secrets:
        - git secret hide -m -d

    test:
        env:
            PIPENV_VERBOSITY: -1
        cmds:
            - pip install pipenv
            - pipenv install --deploy --dev
            - pipenv run isort --recursive --diff .
            - pipenv run black --check .
            - pipenv run flake8
            - pipenv run mypy
            - pipenv run pytest --cov --cov-fail-under=100
