version: '3'
vars:
    BUILD_DIR: pl_worker
    IMAGE_NAME: pl_worker
    DOCKER_FILE: Dockerfile
    HOST: dev
tasks:
# Local Dev
    default:
        silent: false
        interactive: false
        cmds:
            - poetry install
            - task: commit
            - task: test
    commit:
        - task: format
        - task: security
        - task: docs

    setup:
        - python3 -m pip install pipx
        - python3 -m pipx ensurepath
        - pipx install poetry
        - poetry run pre-commit install
    clean:
        - rm -rf dist
        - poetry cache clear _default_cache --all  --no-interaction
        - poetry cache clear PyPI --all  --no-interaction
        - poetry check
        - py3clean .
    security:
        - poetry run whispers {{.BUILD_DIR}} # Check for security issues
        - poetry run bandit --silent -r {{.BUILD_DIR}}
        - poetry run tartufo scan-local-repo .
    test:
        silent: false
        interactive: false
        dotenv: [prod.env]
        cmds:
            - poetry run vulture --min-confidence 100 {{.BUILD_DIR}}
            - poetry run xenon --max-absolute B --max-modules B --max-average B {{.BUILD_DIR}}
#            - poetry run mypy --install-types --non-interactive
#            - poetry run mypy {{.BUILD_DIR}} # Little too aggressive
            - poetry run pytest --cov --cov-fail-under=75 #--typeguard-packages={{.BUILD_DIR}} # Leave typeguard off for now
    format:
        silent: false
        interactive: false
        cmds:
            - poetry run isort --atomic . # Sort imports
            - poetry run black . # Format code
            - poetry run flake8
    docs:
        silent: false
        interactive: false
        cmds:
            - rm -rf docs
            - poetry run pdoc3 {{.BUILD_DIR}} -o docs -f
            - poetry run pyreverse {{.BUILD_DIR}} -d docs
            - poetry run mdformat docs
            - git add docs
    docker-purge: docker system prune -a -f --volumes
    show_secrets:
        - git secret reveal -f
    save_secrets:
        - git secret hide -m -d
    start_webserver: poetry run python3 pl_worker/webserver.py
    start_docker_rootless:
        env: # Due to running root-less on dev box
            DOCKER_HOST: unix:///run/user/1000/docker.sock
        cmds:
            - docker-compose up
    docker_build:
        cmds:
            - docker-compose build
            - docker-compose up # HTTP bind to 80
# Docker
    docker_deploy:
        desc: Deploy to remote docker host
        cmds:
            - rsync -av --filter=':- .gitignore' . root@{{.HOST}}:/{{.FOLDER}}/
            - git secret reveal -f
            - rsync prod.env root@{{.HOST}}:/{{.FOLDER}}/prod.env
            - ssh root@{{.HOST}} 'cd /{{.FOLDER}}/; task setup; task docker;' # Setup Env on remote box
            - rsync -av --delete --filter=':- .gitignore' . root@{{.HOST}}:/{{.FOLDER}}/
    docker: # These are the commands that get run remotely from above
        - docker-compose up -d
