version: '3'
tasks:
    default:
        cmds:
        - task: test
        - task: build
    help:
        silent: true
        cmds:
            - task --list-all

# Dev
    setup:
        env:
            PIPENV_IGNORE_VIRTUALENVS: 1
        ignore_error: true
        cmds:
            - pip install pipenv
            - sudo apt-get install git-secret -y
            - pipenv install --dev
            - pipenv run pre-commit install
    show_secrets:
        - git secret reveal -f
    save_secrets:
        - git secret hide -m -d
    update_pipfile:
        - rm Pipfile
        - rm Pipfile.lock
        - pip freeze > requirements.txt
        - pipenv install --dev -r requirements.txt
        - rm requirements.txt

# Test
    test:
        cmds:
            - task: show_secrets
            - task: test-run
    test-run:
        # We get our secrets from env vars
        # These either get loaded by the python module itself, or via GH Actions
        silent: false
        interactive: true
        env:
            PIPENV_VERBOSITY: -1
        cmds:
            - pipenv run isort --recursive --diff .
            - pipenv run black .
            - pipenv run mypy --install-types --non-interactive
            - pipenv run pytest --cov --cov-fail-under=75

# Docker
    build:
        cmds:
            - sudo docker build . -t porch_light:latest
            - task: show_secrets
    run:
#        dotenv: ['.env']
        cmds:
            - task: build
            - sudo docker run --rm porch_light:latest

# CICD Stuff
    github:
        ignore_error: true
        cmds:
            - pip install pipenv
            - sudo apt-get install git-secret -y
            - pipenv install --dev
            - printenv
            - task: test-run
    commit:
        - task: test
        - task: save_secrets
        - task: show_secrets
    push:
        - task: commit
#        - pipenv run flake8 # Only be picky during push
