version: '3'
tasks:
    default:
        cmds:
        - task: test
        - task: build
    help:
        silent: true
        cmds:
            - task --list-all
    setup:
        ignore_error: true
        cmds:
            - pipenv install --dev
            - sudo apt-get install git-secret -y
            - pipenv run pre-commit install -t pre-commit
            - pipenv run pre-commit install -t pre-push
            - pip install pipenv
            - pipenv install --deploy --dev

    show_secrets:
        - git secret reveal -f >> /dev/null
    save_secrets:
        - git secret hide -m -d >> /dev/null

    test:
        cmds:
            - task: show_secrets
            - task: test-run
    test-run:
        dotenv: ['.env']
        env:
            PIPENV_VERBOSITY: -1
        cmds:
            - pipenv run isort --recursive --diff .
            - pipenv run black --check .
            - pipenv run flake8
            - pipenv run mypy
            - pipenv run pytest --cov --cov-fail-under=100

    commit:
        - task: test
        - task: save_secrets

    build:
        cmds:
            - sudo docker build . -t porch_light:latest
    run:
        cmds:
            - task: test
            - task: build
            - sudo docker run --rm porch_light:latest

