version: '3'
includes:
    docker: ./TaskfileDocker.yaml
    deploy: ./TaskfileDeploy.yaml
    test:   ./TaskfileTest.yaml

tasks:
    default:
        desc: Run full dev cycle
        cmds:
            - task: test
            - task: docker:build
    show_secrets:
        - git secret reveal -f
    save_secrets:
        - git secret hide -m -d
    # CI/CD Stuff
    github:
        ignore_error: true
        cmds:
            - task: test-run
    commit:
        -   task: save_secrets
        -   task: show_secrets
    push:
        -   task: show_secrets
